version: "3"
services:
  nginx:
    image: nginx
    restart: unless-stopped
    ports:
      - "8080:80"
      - "8081:81"
    volumes:
      - "/srv/vsftpd/html:/usr/share/nginx/html"
      - "./conf/nginx.conf:/etc/nginx/nginx.conf"
      - "./conf/conf.d:/etc/nginx/conf.d"
